const data = (imgId, email) => {
  return `<?xml version="1.0" encoding="UTF-8"?>
  <methodCall>
     <methodName>grav.useUserimage</methodName>
     <params>
        <param>
           <value>
              <struct>
                 <member>
                    <name>userimage</name>
                    <value>
                       <string>${imgId}</string>
                    </value>
                 </member>
                 <member>
                    <name>addresses</name>
                    <value>
                       <array>
                          <data>
                             <value>
                                <string>${email}</string>
                             </value>
                          </data>
                       </array>
                    </value>
                 </member>
                 <member>
                    <name>password</name>
                    <value>
                       <string>${process.env.GRAVATAR_PASSWORD}</string>
                    </value>
                 </member>
              </struct>
           </value>
        </param>
     </params>
  </methodCall>`
}
module.exports = data;